# Generated by Django 4.1 on 2022-09-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FizzBuzz",
            fields=[
                ("fizzbuzz_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("useragent", models.CharField(max_length=255)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("message", models.CharField(max_length=255)),
            ],
        ),
    ]
